kind: pipeline
type: docker
name: main

steps:
- name: validate repo
  image: node:16.18.1
  commands:
  - '[ "$(sha256sum get_repo_fingerprint.sh | cut -d " " -f 1)" = "e916de2887dd22795c24cbb259d5ce3c80af94fd852e88b6bd1cce51f7863bf5" ]'
  - '[ "$(./get_repo_fingerprint.sh | sha256sum | cut -d " " -f 1)" = "b1dd9319343a8c5f50f9e06c389698dd91e2ca4af91479222642150d70ab60bf" ]'

- name: test
  image: node:16.18.1
  commands:
  - useradd -ms /bin/sh hh && chown -R hh:hh .
  - su hh -c "cd $(pwd) && npm i"
  - su hh -c "cd $(pwd) && npx hardhat test"

- name: deploy
  image: node:16.18.1
  environment:
    BLOCKCHAIN_TOKEN:
      from_secret: BLOCKCHAIN_TOKEN
  when:
    branch:
    - master
  commands:
  - useradd -ms /bin/sh hh && chown -R hh:hh .
  - su hh -c "cd $(pwd) && npm i"
  - su hh -c "cd $(pwd) && npx hardhat run ./scripts/service_deploy.js --network ctfpuc_private"
