version: "2.4"
services:
  geth:
    build: .
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped

  nginx:
    image: nginx:1.22-alpine
    ports:
      - "48545:8545"
    volumes:
      - ./njs:/etc/nginx/njs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - geth
    restart: unless-stopped

  faucet:
    image: chainflag/eth-faucet:1.1.0
    environment:
      - WEB3_PROVIDER=http://geth:8545
    ports:
      - "8080:8080"
    volumes:
      - ./config/keystore:/app/keystore:ro
      - ./config/password.txt:/app/password.txt:ro
    command: -wallet.keyjson /app/keystore -wallet.keypass /app/password.txt -faucet.minutes 1
    depends_on:
      - geth
    restart: unless-stopped

