version: "2.4"
services:
  geth:
    build: .
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
    pids_limit: 4096
    mem_limit: 4G
    cpus: 8

  nginx:
    image: nginx:1.22-alpine
    ports:
      - "80:8545"
    volumes:
      - ./njs:/etc/nginx/njs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - geth
    restart: unless-stopped
