version: '2.4'

services:
  server:
    image: 'drone/drone:2'
    environment:
      DRONE_GITEA_CLIENT_ID: '35607730-54d8-4135-b27a-773110cc6360'
      DRONE_GITEA_CLIENT_SECRET: 'gto_knauhju4nmvvrs7r3cryhfwlyulddzdevmrcipdyvy72ku23fcba'
      DRONE_GITEA_SERVER: 'https://git.cbsctf.live/'
      DRONE_GIT_ALWAYS_AUTH: 'true'
      DRONE_RPC_SECRET: '4c681ed141dc5f8a65b9b2443d6fb8e6'
      DRONE_SERVER_HOST: 'ci.cbsctf.live'
      DRONE_SERVER_PROTO: 'https'
      DRONE_REGISTRATION_CLOSED: 'false'
      DRONE_REPOSITORY_FILTER: 'ctfcup-2022-final'
      DRONE_USER_FILTER: 'ctfcup-2022-final'
      DRONE_USER_CREATE: 'username:pomo,admin:true'
      DRONE_VALIDATE_PLUGIN_ENDPOINT: 'http://validator:5000'
      DRONE_VALIDATE_PLUGIN_SECRET: '3da8619d0fbc070a54595836d53e720b'
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - "80:80"
    pids_limit: 128
    mem_limit: 2G
    cpus: 2

  validator:
    build: validator
    environment:
      CORRECT_HASHES: 'ctfcup-2022-final/team0:363a3f4cb16bf2706afcbfc9936d504b;ctfcup-2022-final/team1:a66e298e0d776557a83cbb42758e4cec;ctfcup-2022-final/team2:7a84be92354c44207e956d3f82368e75;ctfcup-2022-final/team3:b4350518c1e54b250c6706e6a14f756f;ctfcup-2022-final/team4:02733f7ce3de7fb8e7c899631275df9b'
    restart: unless-stopped
    pids_limit: 128
    mem_limit: 2G
    cpus: 1

