version: '2.4'

services:
  server:
    image: 'drone/drone:2'
    environment:
      DRONE_GITEA_CLIENT_ID: '35607730-54d8-4135-b27a-773110cc6360'
      DRONE_GITEA_CLIENT_SECRET: 'gto_knauhju4nmvvrs7r3cryhfwlyulddzdevmrcipdyvy72ku23fcba'
      DRONE_GITEA_SERVER: 'https://git.cbsctf.live/'
      DRONE_GIT_ALWAYS_AUTH: 'true'
      DRONE_RPC_SECRET: '4c681ed141dc5f8a65b9b2443d6fb8e6'
      DRONE_SERVER_HOST: 'ci.cbsctf.live'
      DRONE_SERVER_PROTO: 'https'
      DRONE_REGISTRATION_CLOSED: 'false'
      DRONE_REPOSITORY_FILTER: 'ctfcup-2022-final'
      DRONE_USER_FILTER: 'ctfcup-2022-final'
      DRONE_USER_CREATE: 'username:pomo,admin:true'
      DRONE_VALIDATE_PLUGIN_ENDPOINT: 'http://validator:5000'
      DRONE_VALIDATE_PLUGIN_SECRET: '3da8619d0fbc070a54595836d53e720b'
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - "80:80"
    pids_limit: 128
    mem_limit: 2G
    cpus: 2

  validator:
    build: validator
    environment:
      CORRECT_HASH: '7d006b59d3099e1916ee67d3efc1b0a1'
      ALLOWED_REPOS: 'ctfcup-2022-final/team0'
    restart: unless-stopped
    pids_limit: 128
    mem_limit: 2G
    cpus: 1

