version: '2.4'

services:
  server:
    image: 'drone/drone:2'
    environment:
      DRONE_GITEA_CLIENT_ID: '35607730-54d8-4135-b27a-773110cc6360'
      DRONE_GITEA_CLIENT_SECRET: 'gto_knauhju4nmvvrs7r3cryhfwlyulddzdevmrcipdyvy72ku23fcba'
      DRONE_GITEA_SERVER: 'https://git.cbsctf.live/'
      DRONE_GIT_ALWAYS_AUTH: 'true'
      DRONE_RPC_SECRET: '4c681ed141dc5f8a65b9b2443d6fb8e6'
      DRONE_SERVER_HOST: 'ci.cbsctf.live'
      DRONE_SERVER_PROTO: 'https'
      DRONE_REGISTRATION_CLOSED: 'false'
      DRONE_REPOSITORY_FILTER: 'ctfcup-2022-final'
      DRONE_USER_FILTER: 'ctfcup-2022-final'
      DRONE_USER_CREATE: 'username:pomo,admin:true'
      DRONE_VALIDATE_PLUGIN_ENDPOINT: 'http://validator:5000'
      DRONE_VALIDATE_PLUGIN_SECRET: '3da8619d0fbc070a54595836d53e720b'
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - "80:80"
    pids_limit: 128
    mem_limit: 2G
    cpus: 2

  validator:
    build: validator
    environment:
      CORRECT_HASHES: 'ctfcup-2022-final/team0:c4fe855a8114b440b74253ae65eb1708;ctfcup-2022-final/team1:7da0e9485616af189ba8e29dad669e9b;ctfcup-2022-final/team2:c7fa08b08b04e0d161dcff8d97ad2473;ctfcup-2022-final/team3:6c997e783f0cf7c5a8e7b0d7b094e53e;ctfcup-2022-final/team4:8b04ab0ea5f3b41099b75b337664d5ad'
    restart: unless-stopped
    pids_limit: 128
    mem_limit: 2G
    cpus: 1

