kind: pipeline
type: docker
name: main

steps:
- name: test
  image: node:16.18.1
  commands:
  - useradd -ms /bin/sh hh && chown -R hh:hh .
  - su hh -c "cd $(pwd) && npm i"
  - su hh -c "cd $(pwd) && npx hardhat test"

- name: deploy
  image: node:16.18.1
  environment:
    BLOCKCHAIN_TOKEN:
      from_secret: BLOCKCHAIN_TOKEN
  when:
    branch:
    - master
  commands:
  - useradd -ms /bin/sh hh && chown -R hh:hh .
  - su hh -c "cd $(pwd) && npm i"
  - su hh -c "cd $(pwd) && npx hardhat run ./scripts/service_deploy.js --network ctfpuc_private"
